### ISSUE TITLE
cause of branking changes in home-assistant 2021.7 the configuration shoud be changed

### ISSUE THREAD

**Issue by honikos** [gabrielpc1190/Home-Assistant_EPEver-eBox-Wifi-01-MODBUS#3]
https://www.home-assistant.io/blog/2021/07/07/release-20217/#new-integrations
As announced in 2021.4, the “old style” YAML was deprecated and now removed
Here is my working home-assistant yaml code for EPEver-eBox-Wifi-01-MODBUS for Tracer AN

#EPEver eBox-Wifi-01 modbus
modbus:
  - type: tcp
    host: host ip address
    port: 8088
    name: hub1
    delay: 1
  - type: rtuovertcp
    host: host ip address
    port: 8088
    name: hub1
    sensors:
      - name: EPEver_Temperatur # später an Batterie anbinden?
        device_class: temperature
        unit_of_measurement: C°
        slave: 1
        address: 12560
        input_type: input
        scale: 0.01
        precision: 2
      - name:  Spannung_Batterie_V # EPEver   #331A
        device_class: voltage
        unit_of_measurement: V
        slave: 1  # slave, which request, 247 possible
        address: 13082
        input_type: input
        scale: 0.01
        precision: 2
      - name: Batterie_Ladestand_SOC #311A State of Charge — hier wohl aus Volt berechnet??
        device_class: battery
        unit_of_measurement: Percent
        slave: 1
        address: 12570
        input_type: input
      - name: PV_Leistung_W # 3102 (L) und 3103 (H)
        device_class: power
        unit_of_measurement: W
        slave: 1
        address: 12546
        input_type: input
        scale: .01
        count: 2
        precision: 2
        swap: word
      - name: PV_Eingangsspannung #3100
        device_class: voltage
        unit_of_measurement: V
        slave: 1
        address: 12544
        input_type: input
        scale: 0.01
      - name: PV_Strom_A # 3101
        device_class: current
        unit_of_measurement: A
        slave: 1
        address: 12545
        input_type: input
        scale: 0.01
        precision: 2

**Comment by honikos** [comment]
made a new branch https://github.com/honikos/Home-Assistant_EPEver-eBox-Wifi-01-MODBUS/tree/patch-1

**Comment by gabrielpc1190** [comment]
That's awesome!
I'm not a programmer, and don't know that much about Home Assistant, I just
like it and I've been learning my way through it to connect my different
devices to it.

I appreciate that you send me this new way of doing this connection.
I no longer have an EPEver since I switched to an all in one inverter.

I don't know how to use GitHub to include your changes into my guide, so
I'll add a link on my guide to yours.

Hope you stay in contact and if you want to share with me some of your home
assistant setup I'll love to read and learn from it!

Cheers 🥂
